### ISSUE TITLE
타이포그래피

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#176]
## 타이포그래피
- 부트스트랩은 영문 사이트를 기준으로 제작되어 있다.(글꼴이 영문을 기준으로 설정되어 있음.)
- 기본 bootstrap.css를 사용하게 되면 윈도우 시스템에서의 한글 글꼴은 브라우저에 따라 시스템 기본 글꼴을 사용할 수도 있고 굴림체가 될 수도 있다.

**[폰트 통일하기]**
1. bootstrap.css 파일 수정
※ 권장하지 않음(파일을 잘못 건들 수도 있음)

bootstrap.css 파일을 에디터로 열어서 body {} 부분을 찾아 아래와 같이 수정한다.
```CSS
body {
      font-family: "Helvetica Neue", Helvetica, Arial, "맑은 고딕", "Malgun gothic", sans-serif;
      ...
}
```
2. 따로 style을 설정해줌 (✔)
- html 문서에 삽입
- 별도의 CSS 파일을 만들어 bootstrap.css 파일 다음에 넣어줌
```CSS
<!-- Bootstrap -->
<link href="css/bootstrap.min.css" rel="stylesheet">
<style>
body {
      font-family: "Helvetica Neue", Helvetica, Arial, "맑은 고딕", "Malgun gothic", sans-serif;
}
</style>
```
```CSS
<!-- Bootstrap -->
<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/custom.css" rel="stylesheet">
```
3. 부트스트랩 웹사이트의 맞춤화 페이지에서 직접 설정함
