### ISSUE TITLE
rem

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#289]
## rem
- 픽셀은 고정된 절대값이기 때문에 접근성을 저해할 수 있다.
- 유저 입장에서 브라우저의 기본 폰트값을 변경하더라도 픽셀값은 변하지 않는다.

**[rem]**
- `rem`은 html의 폰트사이즈를 기준으로 폰트 사이즈를 설정하는 방법이다.
- 일반적으로 대부분의 브라우저 기본 폰트 사이즈는 16px이다.
- html 폰트사이즈를 10px로 설정하면 1.6rem은 16px이 되어 계산이 편리하다. (픽셀과 같이 값이 픽스되는 문제 발생)
- html 폰트 사이즈를 62.5%로 설정하는 방법이 권장된다. (16px의 62.5%가 10px)
```css
html, body {
    font-size: 62.5%;
    line-height: 1.285;
}
```
