### ISSUE TITLE
first rule of flexbox

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#46]
### FIRST RULE :  flexbox에서 항상 direct parent만이 자식의 위치를 움직일 수 있다.

우리는 box를 그 자체로서 포지셔닝하지만 flexbox는 direct하게 포지셔닝하지 않는다.
대신에 해당하는 box를 움직이고 싶다면 해당 box의 바깥쪽에 flexbox container를 만들어야 된다.

**어떻게 flexbox container를 만들까?**
```CSS
body {
       display: flex;
}
```
(↑ body를 flexbox container라고 가정함.)
```html
<body>
   <div class="box">1</div>
   <div class="box">2</div>
   <div class="box">3</div>
</body>
```
```CSS
body {
   display: flex;
}

.box {
   width: 200px;
   height: 200px;
   background: peru;
   color: white;
}
```
(그러면 display: inline-block;과 같은 결과물을 얻을 수 있다.)
