### ISSUE TITLE
main axis & cross axis(flexbox)

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#47]
### main axis & cross axis(flexbox)

flexbox css 세계에는 2가지가 있다 => row와 column
**flex container의 flex-direction 기본값은 row이다. (flex-direction: row)**

- **수평으로 된 item의 위치를 어떻게 바꿀 수 있을까?**

=> position의 속성 중 하나인 `justify-content`를 사용한다. (justify-content는 엄청나게 많은 property를 가지고 있다.)
=> justify-content는 main-axis에 있는 flex children의 위치를 변경한다.

flex-direction: row일 때 수평축이 main axis이다.
main axis에서 justify-content를 사용하면 item을 움직일 수 있다.

main axis 외에 cross axis라는 것도 있다.
cross axis는 main axis와 정반대의 axis를 가진다.

cross axis 방향으로 item을 옮기고 싶을 때는 align-items를 사용한다.

```CSS
.wrapper {
  display: flex;
  justify-content: space-around;
  align-items: flex-start;
  height: 100vh;
}
```
