### ISSUE TITLE
flexbox에서 children을 수정하는 경우들(align-self&order)

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#48]
### align-self
- align-self는 align-item과 비슷한 일을 한다.
- cross axis에 일을 하며 한 box에서만 일을 한다.

```CSS
.child:nth-child(2) {
    align-self: center;
}
```
(2번째 box만 cross axis 방향으로 이동한다.)
### order
- box에게 순서를 변경하라고 할 수 있다.
- html을 변경할 수 없을 때 유용하다.

```CSS
  .child:nth-child(2) {
      order: 1;
  }
```
-> 이렇게 하면 이전에 box 3개가 1, 2, 3 이렇게 있었다고 가정했을 때
1, 3, 2의 순서로 바뀌게 된다.

기본적으로 box의 order는 0이다.
1도 order가 0이고, 3도 order가 0인데 2의 order가 1로 바꼈으니까 맨마지막으로 위치가 보내지게 되는 것이다.
