### ISSUE TITLE
flex-wrap

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#49]
### flex-wrap
flexbox는 비록 너비가 바뀌더라도 item들이 많으면 모두 같은 줄에 있도록 유지한다.
**width를  깨트려서라도 이를 유지함을 확인할 수 있다.**

이는 디폴트로 `flex-wrap: nowrap;`이 설정되어있기 때문이다.
(-> nowrap이 설정되어 있으면 어떻게 되더라도 box들이 같은 줄에 있게 만들어 준다.)

`flex-wrap: wrap;`
-> flexbox에게 child box의 크기를 고려하여 배치되도록 명령한다.

```CSS
.father {
  display: flex;
  /* Main Axis */
  justify-content: space-around;
  /* Cross Axis */
  align-items: center;
  align-content: space-around;
  height: 200vh;
  flex-wrap: wrap;
}
```
