### ISSUE TITLE
flex-grow & flex-shrink

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#51]
### flex-grow & flex-shrink

**flex-shrink**
- flexbox의 children에게 줄 수 있는 property이다.
- flex-shrink는 flexbox가 squeeze될 때 기본적으로 element의 행동을 정의한다.
- flex-shrink의 디폴트 값은 1이다.
- flex-shrink를 2로 바꾸면 2번 box는 기본값에 비해 2배로 줄어든다.
- 어떤 box가 다른 box보다 더 줄어드는 경우가 필요할 때가 있는데 이 경우에 flex-shrink를 사용한다.
```CSS
.child:nth-child(2) {
   background: #000;
   flex-shrink: 2;
}
```

**flex-grow**
- flex-grow는 flex-shrink와 같지만 반대로 작용한다.
- flex-grow의 디폴트 값은 0이다.
```CSS
.child:nth-child(2) {
   background: #000;
   flex-grow: 2;
}
.child:nth-child(3) {
   flex-grow: 1;
}
```
=> 남아있는 공간은 3번 child가 3분의 1, 2번 child가 3분의 2를 가져간다.
