### ISSUE TITLE
flex-basis

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#52]
### flex-basis

child에 적용되는 프로퍼티이다.
flex-basis는 width와 기능적으로 비슷하나 **사실 flex-basis는 element에게 초기값을 주는 것**이다. 늘어지거나 찌그러지기 전의
실제 크기는 아니지만 처음 크기이다. 이 크기는 flex-grow와 flex-shrink에 의해서 바뀌게 된다.

**flex-basis는 main axis에서 일어난다.**

```CSS
.child {
  flex-basis: 30%;
  background: peru;
  color: white;
  font-size: 50px;
}
```
