### ISSUE TITLE
grid-template-columns & grid-template-rows

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#53]
## GRID에 관한 간단한 설명
grid도 flexbox처럼 father과 child로 나뉘어져있고 father에서 제어가 일어난다.
**따라서 대부분의 작업은 father에서 처리된다.**

- grid를 다루기 위해서는 grid에 얼마나 많은 row와 column이 있는지 말해줘야한다.

**[column일 경우]**
[gird-template-columns]
- 여기에 원하는 만큼 column 개수를 원하는 크기만큼 적으면 된다.
[column-gap]
- column들 간의 gap 크기를 결정한다.
[row-gap]
- row들 간의 gap 크기를 결정한다.

**[row일 경우]**
[grid-template-rows]
- row의 크기를 지정해준다.

ex)
```CSS
.father {
   display: grid;
   grid-template-columns: 250px 250px 250px;
   grid-template-rows: 100px 50px 300px;
   column-gap: 5px;
   row-gap: 10px;
}
```
