### ISSUE TITLE
grid-template-areas

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#57]
### grid-template-areas

`grid-template-areas`는 눈에 잘 보이게 layout을 디자인하도록 도와준다.
**[HTML]**
```HTML
<body>
    <div class="grid">
      <div class="header"></div>
      <div class="content"></div>
      <div class="nav"></div>
      <div class="footer"></div>
    </div>
  </body>
```
**[CSS]**
```CSS
.grid {
  display: grid;
  grid-template-columns: auto 200px;
  grid-template-rows: 100px repeat(2, 200px) 100px;
  grid-template-areas:
    "header header header header"
    "content content content nav"
    "content content content nav"
    "footer footer footer footer";
}
```
근데 grid-template-areas를 위와 같이 쓰면 header가 뭔지 content가 뭔지 인식을 못한다.
따라서 우리는 영역의 이름을 지정해줘야한다.
```CSS
.header {
    background-color: #2ecc71;
    grid-area: header
}
```
다음과 같이 영역의 이름을 지정해줄 때는 `grid-area`를 사용한다.
