### ISSUE TITLE
flex

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#60]
# flex

- flex는 flex-grow, flex-shrink, flex-basis를 한 번에 쓸 수 있는 축약형 속성이다.
- 만약 `flex: 1;` 이런 식으로 flex-basis를 생략해서 쓰면 flex-basis는 0이 된다.
- 보통 flex box 내 children을 비율대로 배분하고 싶은 경우에 flex를 이용해서 간단하게 표현한다. 
```CSS
.item {
	flex: 1;
	/* flex-grow: 1; flex-shrink: 1; flex-basis: 0%; */
	flex: 1 1 auto;
	/* flex-grow: 1; flex-shrink: 1; flex-basis: auto; */
	flex: 1 500px;
	/* flex-grow: 1; flex-shrink: 1; flex-basis: 500px; */
}
```
```CSS
.custom-input {
        flex:9;
        border: none;
        outline: none;
        background: transparent;
}
.search-icon-mag {
    flex:1;
    height: 100%;
}
// 9 : 1의 비율로 parent div를 배분한다.
```
