### ISSUE TITLE
직접 웹 폰트 업로드해 사용하기

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#62]
# 직접 웹 폰트 업로드해 사용하기

구글 웹 폰트와 같이 웹 폰트를 제공하는 인터넷 사이트가 있어서 대부분의 경우 링크를 통해 폰트를 사용하나 자신이나 회사에서 만든 웹폰트를 사용할 경우 링크를 이용해서 웹폰트를 적용시킬 수 없다.

### ttf 파일
- 컴퓨터에서 사용하는 글꼴은 TrueType  유형이고 파일 확장자는 `*.ttf`이다.
- 하지만 트루타입 유형의 글꼴은 파일 크기가 너무 커서 다른 유형이 등장했고 대표적으로 `eot`와 `woff`가 있다.
- ttf 파일을 woff 파일로 변환하기 위해서 [https://convertio.co/kr/ttf-woff/](https://convertio.co/kr/ttf-woff/) 사이트를 이용한다.

### 웹 폰트 적용하기
- @font-face 속성을 사용해 웹폰트를 정의할 수 있다. 

```CSS
@font-face {
    font-family: 'trana';
    src: url('trana.woff') format('woff');
}
@font-face {
    font-family: 'Nato Sans Tobesmart edit';
    src: url('../fonts/NotoSansTBE-Light_211026-4.woff') format('woff');
}
```
