### ISSUE TITLE
relative(position)

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#65]
# relative(position)

🎯 `position: relative;`
: element가 처음 위치한 곳을 기준</mark>으로 상하좌우로 움직일 수 있도록 한다.

```CSS
.green {
   background-color: teal;
   height: 100px;
   position: relative;
   top: -10px;
   left: -10px;
   width: 100px;
}
```
