### ISSUE TITLE
combinator

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#67]
# combinator

: 선택자들 사이에 나오는 기호들을 combinator라고 부른다.

**[예시 코드]**
```html
<body>
   <div>
      <p>
         Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod sequi ipsam odio dolorem. <span>inside</span>
      </p>
      <span>hello</span>
   </div>
</body>
```

### Descendant combinator
```CSS
p span {
     color: teal; 
}
```
-> p(father) 안에 있는 span(children)의 색깔을 모두 teal로 바꾼다.
```CSS
div span {
    text-decoration: underline;
}
```
-> div 태그 내에 있는 모든 span(**후손들**)에 underline이 그어진다.

### Child combinator
```CSS
div > span {
   text-decoration: underline;
}
```
-> direct children한테만 underline이 그어진다. (즉, div의 direct children인 span한테만 underline이 그어진다.)

### Adjacent sibling combinator
```CSS
p + span {
    text-decoration: underline;
}
```
-> p 다음으로 오는(**next brother**) span에 underline을 준다.

### General sibling combinator
`+` 는 **바로 옆에 와야지만**(immediately next to it) 적용된다.

**만약 span이 p의 형제인데 바로 뒤에 오지 않을 때**는 `~` combinator를 사용한다.
```CSS
p ~ span {
   text-decoration: underline;
}
```
