### ISSUE TITLE
attribute selector

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#68]
# attribute selector
: attribute selector는 attribute를 통해 어떤 것이든 선택할 수 있게 해준다. 

**[예시 코드]**
```html
<body>
   <div>
      <form>
         <input type="text" placeholder="First name" />
         <input type="text" placeholder="Last name" />
         <input type="password" required placeholder="password" />
      </form>
   </div>
</body>
```
```CSS
input[type="password"]{
   background-color: thistle;
}
```
-> type이 password인 input들이 thistle 배경색을 가지도록 만든다.
```CSS
input[placeholder="username"] {
  background-color: thistle;
}
```
->placeholder가 username인 input들이 thistle 배경색을 가지도록 만든다.
```CSS
input[placeholder~="name"] {
  background-color: pink;
} // 포함하고 있다
```
-> placeholder에 "name"이라는 단어를 **포함한** 모든 input의 배경색이 pink를 가진다.
