### ISSUE TITLE
animation

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#73]
## animation
만약 계속 재생되는 애니메이션을 얻고 싶다면 어떻게 해야 할까?(마우스를 위에 올리거나, transition 없이)
-> animation을 사용하면 어떠한 이벤트 없이도 재생되는 애니메이션을 만들 수 있다.

```CSS
@keyframes coinFlip {
  from {
    transform: rotateX(0);
  }
  to {
    transform:rotateX(360deg);
  }
}
img {
  border: 10px solid black;
  border-radius: 50%;
  animation: coinFlip 5s ease-in-out infinite ; // infinite가 있으면 무한대로 애니메이션이 지속됨
}
```
