### ISSUE TITLE
inherit

### ISSUE THREAD

**Issue by Brylimo** [Brylimo/TIL#90]
### inherit
: inherit은 부모 객체의 값을 가져오는 것이다.

```css
#login-form {
	display: flex;
	flex-direction: column;
	margin: 0px 30px;
}

#login-form a {
	text-align: center;
	text-decoration: none;
	color: inherit;
	font-size: 13px;
}
```
-> `#login-form a`에서 `color: inherit;`을 했는데 이의 부모인 `#login-form`의 color는 검정색이므로 부모 객체의 값인 검정색이 color 값으로 들어가게 된다.
